@startuml
title AppActor LoadWorldMessage

control MainActor as ma
participant AppActor as ac
participant OrientDbActor as orientdba
participant ObjectsDbActor as objectsdba
participant MapBlocksJcsCacheActor as mbjca
control Actor
participant GameSettings

--> ac : LoadWorldMessage

ac -> ac ++ : onLoadWorld()
    alt isUseRemoteServer is true
        ac --> orientdba : ConnectDbRemoteMessage
        ac -> ac ++ : onWrappedDbResponse()
        orientdba --> ac : ConnectDbSuccessMessage
    else
        ac --> orientdba : StartEmbeddedServerMessage
        orientdba --> ac : StartEmbeddedServerSuccessMessage
        ac --> orientdba : ConnectDbEmbeddedMessage
    end
    ac --> Actor : LoadObjectMessage
    note left
    Load WorldMap
    end note
    deactivate ac
deactivate ac

objectsdba --> ac : LoadObjectSuccessMessage
    ac -> ac ++ : onWrappedObjectsResponse()
    alt game object is WorldMap case
    ac --> Actor : CachePutMessage
    ac --> Actor : SetWorldMapMessage
    end
deactivate ac

--> ac : SetWorldMapMessage
ac -> ac ++ : onSetWorldMap()
ac -> GameSettings : setCurrentWorld()
deactivate ac

@enduml
