@startuml
title AppActor createApp
control actor
participant App as a
participant AppActor as ac
participant AppCachesConfig as acc
participant OrientDbActor as orientdba
participant ObjectsDbActor as objectsdba
participant PowerLoomKnowledgeActor as plna
participant KnowledgeJcsCacheActor as kjca
participant KnowledgeBaseActor as kba
participant ConsoleActor as ca

a -> a ++ : createApp()
a -> ac ** : create()
ac -> ac ++ : createActors()
ac -> acc ** : create()

par whenComplete
alt cause is not null
ac --> ac : SetupErrorMessage
else

ac -> ac ++ : createDb()
ac -> orientdba ** : create()

par whenComplete
alt ex is not null
ac --> actor : AppErrorMessage
else

ac -> ac ++ : createObjects()
ac -> objectsdba ** : create()

par whenComplete
alt ex is not null
ac --> actor : AppErrorMessage
else
alt #Lime SkipLoad is false
ac --> actor : LoadWorldMessage
end
end
end
end
end
end
end
deactivate ac

ac -> plna ** : create()
par whenComplete
alt ex is not null
ac --> actor : AppErrorMessage
else

ac -> ac ++ : createKnowledgeCache()
ac -> kjca ** : create()

par whenComplete
alt ex is not null
ac --> actor : AppErrorMessage
else

ac -> ac ++ : createKnowledge()
ac -> kba ** : create()

end
end

deactivate ac
deactivate ac
deactivate ac


ac -> ca ** : create()

deactivate ac
deactivate ac

deactivate a

@enduml
